# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "71c5655fbef433f462fb60e79988add4"
name = "SupplyDesk"
application_url = "https://supplydesk.vercel.app"
embedded = true

[webhooks]
api_version = "2026-01"


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory,read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = ["https://supplydesk.vercel.app/auth/callback"]

[pos]
embedded = false
